services:
    plex:
        container_name: plex
        image: lscr.io/linuxserver/plex:latest
        restart: unless-stopped
        volumes:
            - /mnt/user/appdata/plex/config:/config
            - /mnt/user/appdata/plex/temp:/transcode
            - /mnt/user/appdata/plex:/data
            - /mnt/user/media/Movies:/Movies
            - /mnt/user/media/Music:/Music
            - /mnt/user/media/TV:/TV Shows
            - /mnt/user/media/Youtube:/Youtube
            - /dev/shm:/transcode # set transcode folder in plex settings to /transcode
        ports:
            - 32400:32400/tcp
        environment:
            - PLEX_UID=1000  # Set Plex user to 'jacob' UID
            - PLEX_GID=100   # Set Plex group to 'users' GID
            - PUID=1000
            - PGID=100
            # - UMASK=022
            - TZ=Europe/Stockholm
            - ADVERTISE_IP=https://plex.hjacke.com
            - PLEX_CLAIM=claim-seBxm7jPLh-5oMxN9s4w # get this from plex.tv/claim
            - PLEX_PASS=yes
        network_mode: host
