services:
  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    restart: unless-stopped
    networks:
      - npm_services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omnitools.rule=Host(`tools.hjacke.com`)"
      - "traefik.http.routers.omnitools.entrypoints=websecure"
      - "traefik.http.routers.omnitools.tls=true"
      - "traefik.http.routers.omnitools.tls.certresolver=letsencrypt"
      - "traefik.http.services.omnitools.loadbalancer.server.port=80"

networks:
  npm_services:
    external: true
