services:
    docker-osx:
        image: sickcodes/docker-osx:latest
        container_name: docker-osx-monterey
        devices:
            - /dev/kvm
        ports:
            - "50922:10022"
            - "5999:5999" # maps VNC :99 to host port 5999
        environment:
            GENERATE_UNIQUE: "true"
            MASTER_PLIST_URL: "https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom.plist"
            SHORTNAME: "monterey"
            EXTRA: "-display none -vnc 0.0.0.0:99,password=on"
        stdin_open: true
        tty: true
