services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      br0_docker:
        ipv4_address: 10.0.0.53
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      - TZ=Europe/Stockholm
      - FTLCONF_webserver_port=80
      - FTLCONF_dns_upstreams=9.9.9.9
      #- FTLCONF_dns_upstreams=172.44.0.8#5053 # unbound
      #- FTLCONF_dns_upstreams=9.9.9.9
      #- FTLCONF_dns_upstreams=192.168.1.24#5153 # Cloudflared DoH proxy
      - FTLCONF_webserver_api_password=${PIHOLE_API_KEY}
    volumes:
      - /mnt/user/appdata/pihole/etc-pihole:/etc/pihole/:rw
      - /mnt/user/appdata/pihole/etc-pihole:/var/log/pihole/:rw
    restart: unless-stopped
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=pihole
      - tsdproxy.autodetect=false
      - tsdproxy.container_port=80
    cap_add:
      - NET_ADMIN
      - CAP_CHOWN
      - CAP_SYS_TIME
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_NICE

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    volumes:
      - /mnt/user/appdata/unbound:/opt/unbound/etc/unbound
      - /dev/null:/dev/null:rw
    ports:
      - 5053:53/tcp
      - 5053:53/udp
    networks:
      dns_net:
        ipv4_address: 172.44.0.8
    restart: unless-stopped

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.0.0/16
  br0_docker:
    external: true
