services:
  gluetun_dns:
    image: qmcgaw/gluetun:latest
    networks:
      dns_net:
        ipv4_address: 172.44.0.9
    container_name: gluetun_dns
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # - 6882:6881
      # - 6882:6881/udp
      # - 8388:8388/tcp # Shadowsocks
      # - 8388:8388/udp # Shadowsocks
      - 8001:8000
      - 5053:53/tcp # unbound outbound dns
      - 5053:53/udp # unbound outbound dns
    volumes:
      - /mnt/user/appdata/gluetun_dns:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_ENDPOINT_IP=${WIREGUARD_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${WIREGUARD_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - UPDATER_PERIOD=24h
      - TZ=Europe/Stockholm
    restart: unless-stopped

  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      br0:
        ipv4_address: 192.168.1.53
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    environment:
      - TZ=Europe/Stockholm
      - FTLCONF_webserver_port=80
      - FTLCONF_dns_upstreams=172.44.0.9#5053
      - FTLCONF_webserver_api_password=${PIHOLE_API_KEY}
    volumes:
      - /mnt/user/appdata/pihole/etc-pihole:/etc/pihole/:rw
    restart: unless-stopped
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=pihole
      - tsdproxy.autodetect=false
      - tsdproxy.container_port=80
    depends_on:
      - unbound
    cap_add:
      - NET_ADMIN
      - CAP_CHOWN
      - CAP_SYS_TIME
      - CAP_NET_BIND_SERVICE
      - CAP_SYS_NICE

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    network_mode: service:gluetun_dns
    volumes:
      - /mnt/user/appdata/unbound:/opt/unbound/etc/unbound
      - /dev/null:/dev/null
    depends_on:
      gluetun_dns:
        condition: service_healthy
    restart: unless-stopped

networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.0.0/16
  br0:
    external: true
