version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: jacke         # Replace with your desired username
      POSTGRES_PASSWORD: 7073bd88-c450-4c67-9068-674dfcc6d74c # Replace with your desired password
      POSTGRES_DB: postgres       # Replace with your desired database name
    ports:
      - "5432:5432"
    volumes:
      - /mnt/user/appdata/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8383:8080"