services:
    plex:
        container_name: plex
        image: lscr.io/linuxserver/plex:latest
        restart: unless-stopped
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - /mnt/user/appdata/plex/config:/config
            - /mnt/user/appdata/plex/temp:/transcode
            - /mnt/user/appdata/plex:/data
            - /mnt/user/media/Movies:/Movies
            - /mnt/user/media/Music:/Music
            - /mnt/user/media/TV:/TV Shows
            - /mnt/user/media/Youtube:/Youtube
            - /dev/shm:/transcode # set transcode folder in plex settings to /transcode
        environment:
            - PUID=1000
            - PGID=100
            - TZ=Europe/Stockholm
            - PLEX_PASS=yes
            - PLEX_CLAIM=claim-hzqVrknZUEoSHTJvvxrx
        network_mode: host
