services:
  pacoloco:
    container_name: pacoloco
    image: ghcr.io/anatol/pacoloco
    ports:
      - "9129:9129"
    volumes:
      - /mnt/user/appdata/pacoloco/cache/:/var/cache/pacoloco
      - /mnt/user/appdata/pacoloco/pacoloco.yaml:/etc/pacoloco.yaml
    restart: unless-stopped
    environment:
      - TZ=Europe/Stockholm
