services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    hostname: filebrowser
    restart: unless-stopped
    ports:
      - 7171:80
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/cache:/srv
      - /mnt/cache/appdata/filebrowser/filebrowser.db:/database/filebrowser.db
      - /mnt/user/appdata/filebrowser/settings.json:/config/settings.json
    networks:
      - default
      - npm_services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.hjacke.com`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

networks:
  npm_services:
    external: true
