services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Stockholm
    volumes:
      - /mnt/user/appdata/filebrowser/config:/config
      - /mnt:/srv
    ports:
      - "5800:80"
    restart: unless-stopped
