version: '3.5'

services:
  traefik:
    image: traefik:v2.11
    command: --configFile=/mnt/user/appdata/traefik/traefik.yml
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
       docker0:
    ports:
      - 8050:80
      - 44350:443
      - 8055:8080
    environment:
      - CF_API_EMAIL=jacob.hallgren02@gmail.com
      - CF_DNS_API_TOKEN=LDGx8V_axyv7TKjk2xorwThOO8XVbancKLXq6kt0
      # - CF_API_KEY=YOU_API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/user/appdata/traefik/traefik.yml:/traefik.yml:ro
      - /mnt/user/appdata/traefik/acme.json:/acme.json
      - /mnt/user/appdata/traefik/config.yml:/config.yml:ro
      - /mnt/user/appdata/traefik/logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.hjacke.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$apr1$BXI01Et3$MCFZzi0WR.WHlOSF39qss/"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.hjacke.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=hjacke.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.hjacke.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"


networks:
  docker0:
    name: docker0
    external: true