services:
  trilium:
    image: zadam/trilium:latest
    container_name: trilium
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=trilium
      - net.unraid.docker.icon=https://cdn.lo4d.com/t/icon/128/trilium-notes.png
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - 6161:8080
    volumes:
      - /mnt/user/trilium:/home/node/trilium-data
    restart: unless-stopped
