services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    env_file:
      - .env
    environment:
      - DOCKER_API_VERSION=1.44
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=120
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_DISABLE_CONTAINERS=gluetun-dns gluetun zonos_container soulify postgres 3dcommerce_prod_db muddra_prod_db erpnext_backend erpnext_frontend erpnext_websocket erpnext_queue_short erpnext_queue_long erpnext_scheduler erpnext_configurator erpnext_create_site erpnext_mariadb erpnext_redis_cache erpnext_redis_queue erpnext_redis_socketio
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://${WATCHTOWER_TELEGRAM_BOT_TOKEN}@telegram?chats=${WATCHTOWER_TELEGRAM_CHAT}
      - WATCHTOWER_ROLLING_RESTART=true
      - DOCKER_CONFIG=/config
      # HTTP API for webhook triggers
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_API_TOKEN}
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    expose:
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker:/config:ro
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
