tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/hjacke.com-fullchain.pem
        keyFile: /etc/traefik/certs/hjacke.com-privkey.pem
  certificates:
    # Wildcard certificate for *.hjacke.com
    - certFile: /etc/traefik/certs/hjacke.com-fullchain.pem
      keyFile: /etc/traefik/certs/hjacke.com-privkey.pem
    # Wildcard certificate for *.lokalhome.duckdns.org
    - certFile: /etc/traefik/certs/lokalhome.duckdns.org-fullchain.pem
      keyFile: /etc/traefik/certs/lokalhome.duckdns.org-privkey.pem
    # Certificate for overseerr.lokalhome.duckdns.org
    - certFile: /etc/traefik/certs/overseerr.lokalhome.duckdns.org-fullchain.pem
      keyFile: /etc/traefik/certs/overseerr.lokalhome.duckdns.org-privkey.pem




