services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    security_opt:
      - apparmor:rootlesskit #optional
    environment:
      - PUID=1000
      - PGID=100
      - KASM_PORT=6333
    volumes:
      - /mnt/cache/appdata/kasm/data:/opt
      - /mnt/cache/appdata/kasm/profiles:/profiles
    ports:
      - 6333:6333
    restart: unless-stopped
