services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/sonarr/config:/config
      - /mnt/user/media/TV:/tv
      - /mnt/user/downloads/qbitorrent:/downloads
    ports:
      - 8989:8989
    networks:
      - npm_services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.hjacke.com`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=99
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/binhex-radarr:/config
      - /mnt/user/media/Movies:/movies
      - /mnt/user/downloads/qbitorrent:/downloads
    ports:
      - 7878:7878
    networks:
      - npm_services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.hjacke.com`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/bazarr/config:/config
      - /mnt/user/media:/media
    ports:
      - 6767:6767
    networks:
      - npm_services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.hjacke.com`)"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.tls.certresolver=letsencrypt"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    restart: unless-stopped

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    hostname: seerr
    restart: unless-stopped
    networks:
      - npm_services
    ports:
      - "5055:5055"
    volumes:
      - /mnt/user/appdata/overseerr:/app/config
      - /mnt/user/media:/media
    environment:
      - TZ=Etc/UTC
      - PORT=5055
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seerr-filmen.rule=Host(`filmen.hjacke.com`)"
      - "traefik.http.routers.seerr-filmen.entrypoints=websecure"
      - "traefik.http.routers.seerr-filmen.tls=true"
      - "traefik.http.routers.seerr-filmen.tls.certresolver=letsencrypt"
      - "traefik.http.services.seerr.loadbalancer.server.port=5055"

networks:
  npm_services:
    external: true
