services:
  kimai:
    image: lscr.io/linuxserver/kimai:latest
    container_name: kimai
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Stockholm
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - /mnt/user/appdata/kimai/config:/config
    ports:
      - 3380:80
      - 33443:443
    restart: unless-stopped
