services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8080:8080 # qbittorrent
      - 8000:8000 # http server
      - 5030:5030 # slskd
      - 5031:5031 # slskd
      - 50300:50300 # slskd
      - 11470:11470 #stremio-server
      - 12470:12470 #stremio-server https
      - 6565:6565 # nicotineplus
      - 2234:2234 # nicotineplus
      - 7474:7474 # autobrr
    volumes:
      - /mnt/user/appdata/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=${VPN_TYPE}
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=Europe/Stockholm
      - UPDATER_PERIOD=24h
    restart: unless-stopped

  qBittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qBittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/downloads/qbitorrent:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  nicotineplus-proper:
    image: sirjmann92/nicotineplus-proper:latest
    container_name: nicotine
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - TZ=Europe/Stockholm
      - UMASK=022
      - DARKMODE=True
      - LOGIN=${NICOTINE_USER}
      - PASSW=${NICOTINE_PASSW}
      - PUID=1000
      - PGID=100
      - UPNP=False
      - AUTO_CONNECT=True
      - TRAY_ICON=False
      - WEB_UI_PORT=6565
    volumes:
      - /mnt/user/downloads/soulseek:/downloads
      - /mnt/user/downloads/soulseek/incomplete:/incomplete
      - /mnt/user/music:/music:rw
      - /mnt/user/media/Youtube:/youtube-paywall:rww
      - /mnt/user/podcasts:/podcasts:rw
      - /mnt/user/syncthing/qqq:/nsfw:rw
      - /mnt/user/appdata/nicotineplus-proper/config:/config
      - /mnt/user/appdata/nicotineplus-proper/data:/data
    restart: unless-stopped
