services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080 # qbittorrent
      - 5030:5030 # slskd
      - 5031:5031 # slskd
      - 50300:50300 # slskd
      
    volumes:
      - /mnt/user/appdata/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom  # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_TYPE=${VPN_TYPE}
      - VPN_ENDPOINT_IP=${VPN_ENDPOINT_IP}
      - VPN_ENDPOINT_PORT=${VPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=Europe/Stockholm
      - UPDATER_PERIOD=24h

  qBittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qBittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/downloads:/downloads
    depends_on:
      - gluetun
    restart: always

  slskd:
    image: slskd/slskd
    container_name: slskd
    network_mode: "service:gluetun"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /mnt/user/appdata/slskd:/app
    restart: always
    depends_on:
      - gluetun