services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/dockhand/data:/app/data
    networks:
      - npm_services
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=npm_services"
      - "traefik.http.routers.dockhand.rule=Host(`dockhand.hjacke.com`)"
      - "traefik.http.routers.dockhand.entrypoints=websecure"
      - "traefik.http.routers.dockhand.tls=true"
      - "traefik.http.routers.dockhand.tls.certresolver=letsencrypt"
      - "traefik.http.services.dockhand.loadbalancer.server.port=3000"
      - "net.unraid.docker.icon=https://avatars.githubusercontent.com/u/80454229?s=48&v=4"
    environment:
      - TZ=Europe/Stockholm
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  npm_services:
    external: true
